Repository 2024FALL-SWPP/team-project-for-2024-fall-swpp-team-20, pull requests merged in 2024-11, with the labels that each got.

#24 Feat/21 lint automation
  .gitconfig
  .githooks/pre-commit
  .gitignore
  Assets/Editor.meta
  Assets/Editor/InstallGitHooks.cs
  Assets/Editor/InstallGitHooks.cs.meta
  Assets/Scripts/CameraController.cs
  Assets/Scripts/Managers/GameManager.cs
  Assets/Scripts/Managers/PlayManager.cs
  Assets/Scripts/Managers/SoundManager.cs
  Assets/Scripts/Managers/UIManager.cs
  Assets/Scripts/MapController.cs
  Assets/Scripts/PlayerController.cs
  Packages/manifest.json
  Packages/packages-lock.json
Labels: project management

#60 feat : digital clock anomaly
  Assets/Prefabs/Map.prefab
  Assets/Scripts/Anomaly/EasyDigitalClockAnomaly.cs
  Assets/Scripts/Anomaly/EasyDigitalClockAnomaly.cs.meta
  Assets/Scripts/Managers/PlayManager.cs
  Assets/Scripts/MapController.cs
Labels: feature

#62 Fix: MapController 변경
  Assets/Scripts/Anomaly/Anomaly.cs
  Assets/Scripts/Anomaly/EasyLaptopAnomaly.cs
  Assets/Scripts/MapController.cs
Labels: feature

#67 Feat : implemented book color anomaly
  Assets/Prefabs/Map.prefab
  Assets/Scripts/Anomaly/EasyBookColorAnomaly.cs
  Assets/Scripts/Anomaly/EasyBookColorAnomaly.cs.meta
Labels: feature

#69 Feat : implement book disappear anomaly
  Assets/Scripts/Anomaly/EasyBookDisappearAnomaly.cs
  Assets/Scripts/Anomaly/EasyBookDisappearAnomaly.cs.meta
Labels: feature

#91 Feat/90 change paint and chair anomaly
  Assets/Prefabs/Map.prefab
  Assets/Scenes/GameScene.unity
  Assets/Scripts/Anomaly/EasyCanvasChangeAnomaly.cs
  Assets/Scripts/Anomaly/EasyCanvasChangeAnomaly.cs.meta
  Assets/Scripts/Anomaly/EasyChairLegDisappearAnomaly.cs
  Assets/Scripts/Anomaly/EasyChairLegDisappearAnomaly.cs.meta
Labels: feature

#105 Feat/104 teddy bear and cube anomaly
  Assets/Prefabs/Map.prefab
  Assets/Scenes/GameScene.unity
  Assets/Scripts/Anomaly/EasyCubeAnomaly.cs
  Assets/Scripts/Anomaly/EasyCubeAnomaly.cs.meta
  Assets/Scripts/Anomaly/EasyTeddyBearAnomaly.cs
  Assets/Scripts/Anomaly/EasyTeddyBearAnomaly.cs.meta
Labels: feature

#120 fix not to pass through the object
  Assets/Prefabs/Map.prefab
  Assets/Scripts/InteractionHandler.cs
  Assets/Scripts/Managers/StageManager.cs
Labels: bug

#130 Feat/129 drawer and dresser anomaly
  Assets/Scenes/GameScene.unity
  Assets/Scripts/Anomaly/EasyDrawerMissingContentAnomaly.cs
  Assets/Scripts/Anomaly/EasyDrawerMissingContentAnomaly.cs.meta
  Assets/Scripts/Anomaly/EasyDresserBackOpenAnomaly.cs
  Assets/Scripts/Anomaly/EasyDresserBackOpenAnomaly.cs.meta
Labels: feature

#135 fixed bug issue#34
  Assets/Scripts/InteractionHandler.cs
  Assets/Scripts/Managers/GameManager.cs
Labels: bug

#138 Fix/136 change hard anomaly info
  Assets/Assets MOOD WARE/_MW Skybox/MAT/Skybox 26_pan.mat
  Assets/InputSystem/Control.cs
  Assets/InputSystem/InputAction.inputactions
  Assets/InputSystem/Laptop.inputactions
  Assets/InputSystem/Laptop.inputactions.meta
  Assets/InputSystem/LaptopSystem.cs
  Assets/InputSystem/LaptopSystem.cs.meta
  Assets/Prefabs/Map.prefab
  Assets/Scenes/GameScene.unity
  Assets/Scripts/Anomaly/EasyLaptopAnomaly.cs
  Assets/Scripts/Anomaly/HardAnomaly.cs
  Assets/Scripts/Anomaly/HardLavaAnomaly.cs
  Assets/Scripts/Anomaly/HardTimeBombAnomaly.cs
  Assets/Scripts/Interactions/Laptop.cs
  Assets/Scripts/Managers/UIManager.cs
  Assets/Scripts/MapController.cs
  Assets/Scripts/PlayerController.cs
Labels: enhancement

#148 implement reverse map anomaly
  Assets/Scenes/GameScene.unity
  Assets/Scripts/Anomaly/HardAnomaly.cs
  Assets/Scripts/Anomaly/HardReverseMapAnomaly.cs
  Assets/Scripts/Anomaly/HardReverseMapAnomaly.cs.meta
  Assets/Scripts/Managers/UIManager.cs
Labels: feature
